version: '3'

services:
  db:
    image: mysql:latest
    container_name: django_mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: recipes
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: django_web
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
